## Numpy
- 파이썬에서 수학적 계산을 쉽게 할 수 있도록 도와주는 라이브러리

In [2]:
# 모듈 불러오기
import numpy as np 

In [4]:
# 1차원 배열 생성
arr = np.array(["A", "B", "C", "D", "E"])
arr
# <U1 = string

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

In [8]:
print(arr.shape) # 요소의 개수
print(arr.ndim) # 차원
print(arr.dtype) # data type => 공통적인 데이터 타입

(5,)
1
<U1


In [12]:
# 2차원 배열 생성
arr2 = np.array([["A","B", "C"], ["D", "E", "F"]])
arr2 

array([['A', 'B', 'C'],
       ['D', 'E', 'F']], dtype='<U1')

In [14]:
print(arr2.shape)
print(arr2.ndim) 
print(arr2.dtype)

(2, 3)
2
<U1


In [21]:
# 3차원 배열 생성
arr3 = np.array([[["A","B"], ["C", "D"]],[["E","F"],["G","H"]]]) 
arr3

array([[['A', 'B'],
        ['C', 'D']],

       [['E', 'F'],
        ['G', 'H']]], dtype='<U1')

In [23]:
print(arr3.shape)
print(arr3.ndim) 
print(arr3.dtype)

(2, 2, 2)
3
<U1


### 1) Numpy 형상 관련 함수

In [27]:
arr4 = np.array(["1","2","3","4","5"])
print(arr4.dtype)

arr4 = arr4.astype(np.float64) # 원하는 타입으로 바꿀 때 astype을 사용한다.
print(arr4.dtype)

<U1
float64


### 2) Numpy 인덱싱 & 슬라이싱

In [35]:
# 인덱싱
arr = np.arange(1, 10)

print(arr)
print(arr[:3])

print(arr[arr>6]) # 6보다 큰 데이터보다 큰 값을 가져오기



[1 2 3 4 5 6 7 8 9]
[1 2 3]
[7 8 9]


### 3) Numpy 연산

In [37]:
# 배열 연산
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

add =np.add(arr1, arr2)
print(add)

[[ 6  8]
 [10 12]]
